baseURL = "https://laphael58.github.io/"
languageCode = "ko-kr"
title = "Hack-and-Grow"
theme = "PaperMod"
relativeURLs = false
canonifyURLs = true
summaryLength = 30

[params]
customCSS = ["css/custom.css"]

[params.profileMode]
enabled = true
title = "ì‹ ìŠ¹í™˜"
subtitle = "ê³ ë ¤ëŒ€í•™êµ ì¸ê³µì§€ëŠ¥ì‚¬ì´ë²„ë³´ì•ˆí•™ê³¼ 25í•™ë²ˆ<br>AICS 25 | KOREA UNIV"
imageUrl = "https://www.korea.ac.kr/sites/ko/images/contents/emblem_1.png"
imageWidth = 200
imageHeight = 200

[[params.profileMode.buttons]]
name = "Blog"
url = "/posts/"

[[params.profileMode.buttons]]
name = "Archive"
url = "/archive/"

[[params.profileMode.buttons]]
name = "About"
url = "/about/"

[[params.socialIcons]]
    name = "Github"
    url = "https://github.com/laphael58"

[[params.socialIcons]]
    name = "Instagram"
    url  = "https://www.instagram.com/tlstmdghks_/"

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[permalinks]
posts = "/:slug/"

[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 2

  [[menu.main]]
  name = "Archive"
  url = "/archive/"
  weight = 3

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4

  [[menu.main]]
  name = "ğŸ”ï¸"
  url = "/search/"
  weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]