baseURL = "https://laphael58.github.io/"
languageCode = "ko-kr"
title = "Hack-and-Grow"
theme = "PaperMod"
relativeURLs = false
canonifyURLs = true

[permalinks]
posts = "/:slug/"

[menu]
  [[menu.main]]
    name = "블로그"
    url = "/"
    weight = 1